[project]
name = "pyquotex"
version = "0.1.0"
description = ""
authors = [
    {name = "cleiton",email = "cleiton.leonel@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "websocket-client (>=1.8.0,<2.0.0)",
    "playwright (==1.44.0)",
    "beautifulsoup4 (>=4.13.3,<5.0.0)",
    "numpy (>=2.2.3,<3.0.0)",
    "pyfiglet (>=1.0.2,<2.0.0)",
    "playwright-stealth (>=1.0.6,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
